### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Error'

### ISSUE THREAD

**Issue by kenorb** [Te-k/phpscanner#3]
```
$ ./phpscanner/phpscanner.py trunk/
Traceback (most recent call last):
  File "./phpscanner/phpscanner.py", line 231, in <module>
    res = scanner.scan_file(os.path.join(root, name))
  File "./phpscanner/phpscanner.py", line 138, in scan_file
    res = self.check_file(path)
  File "./phpscanner/phpscanner.py", line 94, in check_file
    sigs = self.check_file_signature(path)
  File "./phpscanner/phpscanner.py", line 84, in check_file_signature
    except yara.Error:
AttributeError: 'module' object has no attribute 'Error'
```

```
$ pip2 list | grep yara
yara (1.7.7)
```

**Comment by Te-k** [comment]
You have to install yara-python from the source : http://yara.readthedocs.io/en/v3.4.0/gettingstarted.html#compiling-yara

```
> pip2 list | fgrep yara
yara-python (3.4.0)
```
